export { default as Footer } from './Footer/footer'
export { default as FormContainer } from './FormContainer/formContainer'
export { default as Header } from './Header/header'
export { default as MainContent } from './MainContent/mainContent'
export { default as NavBar } from '../containers/NavBar/navBar'
